### ISSUE TITLE
Deutsch can't be used due to error in \Titelblatt

### ISSUE THREAD

**Issue by meyerpp** [ISTE-SQA/template-thesis-proposal#1]
There are missing several translations for the uni-stuttgart-cs-cover.sty 

![grafik](https://user-images.githubusercontent.com/23094908/34948500-946ea5c0-fa0d-11e7-8457-f9935e131951.png)

These lines have to be added, so that the \Titelblatt works for german too.

**Comment by spethso** [comment]
@AlirezaHakamian, can you adapt directly with the new institute and group name this when you update the template?

**Comment by AlirezaHakamian** [comment]
> @AlirezaHakamian, can you adapt directly with the new institute and group name this when you update the template?

Yeah, I changed them

**Comment by spethso** [comment]
It seems this issue is resolved now. Therefore, I will close it for now.
